name: 'Keep-a-Changelog-Merge'
description: 'Keep your Changelog.md in sync with your development branch to prevent merge conflicts.'
inputs:
  remote:
    description: 'The file path of the CHANGELOG.md which you are syncing with. (eg. Copied from your default branch)'
    required: true
    default: ${{ github.event.repository.default_branch }}
  local:
    description: 'The CHANGELOG.md file path'
    required: false
    default: "./CHANGELOG.md"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --source ${{ inputs.local }}
    - --destination ${{ inputs.remote }}
    - --output ${{ inputs.local }}